WorkFromHome/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WorkFromHome.Models
{
    public class Department
    {
        [Key]
        public int DepartID { get; set; }
        public string DepartName { get; set; }
    }
}

WorkFromHome/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkFromHome.App_Start;
using WorkFromHome.Helper;
using WorkFromHome.Models;

namespace WorkFromHome.Controllers
{
    [CustomAuthorize("Administration")]
    public class DepartmentsController : Controller
    {
        private WFHContext db = new WFHContext();
        // GET: Departments
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DepartmentLists()
        {
            return PartialView(db.Departments.ToList());
        }


        //Add and Update Method
        #region PostMethods

        [HttpPost]
        public JsonResult AddDepartment(Department department)
        {
            var status = false;
            db.Departments.Add(department);
            db.SaveChanges();
            status = true;
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        public JsonResult EditDepartment(int? id)
        {
            bool status = false;
            if (id == null)
            {
                return Json(status, JsonRequestBehavior.AllowGet);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return Json(status, JsonRequestBehavior.AllowGet);
            }
            return Json(department, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateDepartment(Department department)
        {
            var status = false;
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                status = true;
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        #endregion


        public JsonResult DeleteConfirmed(int id)
        {
            var status = false;
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            status = true;
            return Json(status, JsonRequestBehavior.AllowGet);
        }
    }
}

WorkFromHome/Views/Departments/DepartmentLists.cshtml
@model IEnumerable<WorkFromHome.Models.Department>


<table id="example1" width="100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DepartName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartName)
                </td>
                <td>
                    <a href='#' class='btn btn-success' onclick="@("EditDepart('" + item.DepartID + "')")"> <span class='fa fa-edit' style="color: white; font-size: 20px;"></span></a> &nbsp; &nbsp; &nbsp; &nbsp;
                    <a href='#' class='btn btn-danger' onclick="@("DeleteDepart('" + item.DepartID + "')")"> <span class='fa fa-remove' style='color: white; font-size: 20px;'></span> </a>

                </td>
            </tr>
        }
    </tbody>
</table>

WorkFromHome/Views/Departments/Index.cshtml
@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link rel="stylesheet" href="~/template/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<style>

    .example-modal .modal {
        position: relative;
        top: auto;
        bottom: auto;
        right: auto;
        left: auto;
        display: block;
        z-index: 1;
    }

    .example-modal .modal {
        background: transparent !important;
    }
</style>

<br />
<section class="content-header">
    <h1>
        Departments
    </h1>
   
</section>
<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add Department</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal">
            <div class="box-body">
                <div class="form-group">
                    <label for="departName" class="col-sm-2 control-label">Department Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="departName" placeholder="Department Name">
                    </div>
                </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="button" onclick="AddDepartment()" class="btn btn-info pull-right">Add Department</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Departments List</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body" id="dataContainer">
            @{ Html.RenderAction("DepartmentLists", "Departments");}

        </div>
        <!-- /.box-body -->
    </div>

    <div class="modal fade" id="editModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Edit Department</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="DepartID" />
                    <label>Department Name</label>
                    <input type="text" id="editDepartName" name="eDistrictEnglish" class="form-control" required />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="UpdateDepart()">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="deleteModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Delete</h4>
                </div>
                <div class="modal-body">
                    <p>Are You Sure you want to Delete this Department&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary" onclick="DeleteConfirmed()">Yes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    </section>

    @section scripts
    {

        <!-- DataTables -->
        <script src="~/template/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="~/template/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>




        <script>

         $(function () {
    $('#example1').DataTable()

    })

         function GetList() {
             $.ajax({
                    url: '@Url.Action("DepartmentLists", "Departments")'

                }).done(function(result) {
                    $('#dataContainer').html(result);
                     $('#example1').DataTable()
                    console.log(result)
                 }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                     console.log(textStatus)
                     console.log(errorThrown)
                     alert("Something Went Wrong, Try Later");
                 });
        }
        //Save New Record
        function AddDepartment(){
            if ($("#departName").val() == "") {
                $("#departName").focus();
                return false;
            }

            var formData = new FormData();
            formData.append("DepartName", $("#departName").val());
            var url = "/Departments/AddDepartment";
            $.ajax({
                url: url,
                type: 'POST',
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                success: function (data) {
                    if (data == true) {
                        alert("Department Added Successfully");
                        $("#departName").val("");
                    }
                    else {
                        alert("Error Occured,Please Try Later");
                    }
                    GetList();
                },
                error: function () {
                    alert("Something Went Wrong, Try Later");
                }
            });
        }

        var deleteID, departmentDetail;
        //Show Modal on Delete and Edit Clicks
        function EditDepart(ID) {
            $.ajax({
                type: 'GET',
                url: '/Departments/EditDepartment',
                data: { id: ID },
                success: function (data) {
                    $("#editModal").modal();
                    $("#DepartID").val(data.DepartID);
                    $("#editDepartName").val(data.DepartName);
                    districtDetail = data;
                },
                error: function () {
                    alert("Something went wrong while loading record...");
                }

            });

        }

        function DeleteDepart(TypeID) {
            $("#deleteModal").modal();
            deleteID = TypeID;

        }

        // Save Edit Data and Delete Data
        function UpdateDepart() {
            if ($("#editDepartName").val() == "") {
                $("#editDepartName").focus();
                return false;
            }


            var formData = new FormData();
            formData.append("DepartID", $("#DepartID").val());
            formData.append("DepartName", $("#editDepartName").val());

            var url = "/Departments/UpdateDepartment";
            $.ajax({
                url: url,
                type: 'POST',
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                success: function (data) {
                    if (data == true) {
                        alert("Department Updated Successfully");
                        $("#editDepartName").val("");
                        $("#DepartID").val("");
                        $('#editModal').modal('hide');
                    }
                    else {
                        alert("Something Went Wrong, Try Later");
                        $('#editModal').modal('hide');
                    }
                    GetList();
                },
                error: function () {
                    alert("Something Went Wrong, Try Later");
                }
            });
        }

        function DeleteConfirmed() {
            $.ajax({
                type: "GET",
                url: '/Departments/DeleteConfirmed',
                data: { id: deleteID },
                success: function (status) {
                    alert("Record has been deleted")
                    $('#deleteModal').modal('hide');
                    GetList()
                },
                error: function () {
                    alert("Something Went Wrong, Try Later");
                }
            });
        }

        </script>

    }